run:
  go: '1.22'

linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - forbidigo
  - forcetypeassert
  - gci
  - gocritic
  - godot
  - err113
  - gofmt
  - gofumpt
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - interfacebloat
  - lll
  - loggercheck
  - makezero
  - misspell
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - staticcheck
  - stylecheck
  - tagliatelle
  - testableexamples
  - tenv
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - rowserrcheck
  - sqlclosecheck
  - wastedassign
  - asasalint
  - canonicalheader
  - containedctx
  - copyloopvar
  - fatcontext
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecksumtype
  - iface
  - inamedparam
  - intrange
  - mirror
  - musttag
  - perfsprint
  - protogetter
  - recvcheck
  - sloglint
  - spancheck
  - tagalign
  - testifylint
  - usestdlibvars
  - zerologlint
  disable:
  - cyclop
  - exhaustive
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomoddirectives
  - ireturn
  - maintidx
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nonamedreturns
  - paralleltest
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl
  - mnd
  - depguard

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-geobabel)
  gofumpt:
    extra-rules: true
    module-path: github.com/twpayne/go-geobabel
  goimports:
    local-prefixes: github.com/twpayne/go-geobabel
  misspell:
    locale: US
  stylecheck:
    checks:
    - all

issues:
  include:
  - EXC0011